#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposantBD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTPCom")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertArticles(Articles instance);
    partial void UpdateArticles(Articles instance);
    partial void DeleteArticles(Articles instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ComposantBD.Properties.Settings.Default.BDTPComConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Articles> Articles
		{
			get
			{
				return this.GetTable<Articles>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articles")]
	public partial class Articles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code_article;
		
		private string _Titre_article;
		
		private string _Type_article;
		
		private System.Nullable<int> _Frais_soumission;
		
		private System.Nullable<int> _Nombre_page;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCode_articleChanging(int value);
    partial void OnCode_articleChanged();
    partial void OnTitre_articleChanging(string value);
    partial void OnTitre_articleChanged();
    partial void OnType_articleChanging(string value);
    partial void OnType_articleChanged();
    partial void OnFrais_soumissionChanging(System.Nullable<int> value);
    partial void OnFrais_soumissionChanged();
    partial void OnNombre_pageChanging(System.Nullable<int> value);
    partial void OnNombre_pageChanged();
    #endregion
		
		public Articles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_article", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Code_article
		{
			get
			{
				return this._Code_article;
			}
			set
			{
				if ((this._Code_article != value))
				{
					this.OnCode_articleChanging(value);
					this.SendPropertyChanging();
					this._Code_article = value;
					this.SendPropertyChanged("Code_article");
					this.OnCode_articleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titre_article", DbType="NChar(10)")]
		public string Titre_article
		{
			get
			{
				return this._Titre_article;
			}
			set
			{
				if ((this._Titre_article != value))
				{
					this.OnTitre_articleChanging(value);
					this.SendPropertyChanging();
					this._Titre_article = value;
					this.SendPropertyChanged("Titre_article");
					this.OnTitre_articleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_article", DbType="NChar(10)")]
		public string Type_article
		{
			get
			{
				return this._Type_article;
			}
			set
			{
				if ((this._Type_article != value))
				{
					this.OnType_articleChanging(value);
					this.SendPropertyChanging();
					this._Type_article = value;
					this.SendPropertyChanged("Type_article");
					this.OnType_articleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frais_soumission", DbType="Int")]
		public System.Nullable<int> Frais_soumission
		{
			get
			{
				return this._Frais_soumission;
			}
			set
			{
				if ((this._Frais_soumission != value))
				{
					this.OnFrais_soumissionChanging(value);
					this.SendPropertyChanging();
					this._Frais_soumission = value;
					this.SendPropertyChanged("Frais_soumission");
					this.OnFrais_soumissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_page", DbType="Int")]
		public System.Nullable<int> Nombre_page
		{
			get
			{
				return this._Nombre_page;
			}
			set
			{
				if ((this._Nombre_page != value))
				{
					this.OnNombre_pageChanging(value);
					this.SendPropertyChanging();
					this._Nombre_page = value;
					this.SendPropertyChanged("Nombre_page");
					this.OnNombre_pageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
